<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" total="3" passed="0">
	<reporter-output>
	</reporter-output>
	<suite name="Default suite" duration-ms="15139" started-at="2017-01-18T14:57:17Z"
		finished-at="2017-01-18T14:57:33Z">
		<groups>
			<group name="">
				<method
					signature="TestCases.TC001_login_validation()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="TC001_login_validation" class="com.framework.testCases.TestCases" />
				<method
					signature="TestCases.TC003_checkGiftCardFunctionality()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="TC003_checkGiftCardFunctionality" class="com.framework.testCases.TestCases" />
			</group> <!-- -->
			<group name="Dev">
				<method
					signature="TestCases.TC002_fassured_validation()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="TC002_fassured_validation" class="com.framework.testCases.TestCases" />
			</group> <!-- Dev -->
		</groups>
		<test name="Default test" duration-ms="15139" started-at="2017-01-18T14:57:17Z"
			finished-at="2017-01-18T14:57:33Z">
			<class name="com.framework.testCases.TestCases">
				<test-method status="FAIL"
					signature="setup()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="setup" is-config="true" duration-ms="0" started-at="2017-01-18T20:27:17Z"
					finished-at="2017-01-18T20:27:17Z">
					<exception class="java.io.FileNotFoundException">
						<message>
              <![CDATA[D:\MobileAppTesting\script\TestLabPro\src\test\resources\EnvironmentVars (The system cannot find the path specified)]]>
						</message>
						<full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: D:\MobileAppTesting\script\TestLabPro\src\test\resources\EnvironmentVars (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.framework.utilities.tcdf.globalValue(tcdf.java:13)
	at com.framework.pageFactory.TestBase.setup(TestBase.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
						</full-stacktrace>
					</exception> <!-- java.io.FileNotFoundException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- setup -->
				<test-method status="SKIP"
					signature="TC001_login_validation()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="TC001_login_validation" duration-ms="7" started-at="2017-01-18T20:27:18Z"
					finished-at="2017-01-18T20:27:18Z">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- TC001_login_validation -->
				<test-method status="FAIL"
					signature="teardown()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="teardown" is-config="true" duration-ms="0" started-at="2017-01-18T20:27:18Z"
					finished-at="2017-01-18T20:27:18Z">
					<exception class="java.lang.NullPointerException">
						<full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.framework.pageFactory.TestBase.teardown(TestBase.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.NullPointerException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- teardown -->
				<test-method status="SKIP"
					signature="setup()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="setup" is-config="true" duration-ms="0" started-at="2017-01-18T20:27:23Z"
					finished-at="2017-01-18T20:27:23Z">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- setup -->
				<test-method status="SKIP"
					signature="TC002_fassured_validation()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="TC002_fassured_validation" duration-ms="3" started-at="2017-01-18T20:27:23Z"
					finished-at="2017-01-18T20:27:23Z">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- TC002_fassured_validation -->
				<test-method status="FAIL"
					signature="teardown()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="teardown" is-config="true" duration-ms="0" started-at="2017-01-18T20:27:23Z"
					finished-at="2017-01-18T20:27:23Z">
					<exception class="java.lang.NullPointerException">
						<full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.framework.pageFactory.TestBase.teardown(TestBase.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.NullPointerException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- teardown -->
				<test-method status="SKIP"
					signature="setup()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="setup" is-config="true" duration-ms="0" started-at="2017-01-18T20:27:28Z"
					finished-at="2017-01-18T20:27:28Z">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- setup -->
				<test-method status="SKIP"
					signature="TC003_checkGiftCardFunctionality()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="TC003_checkGiftCardFunctionality" duration-ms="2"
					started-at="2017-01-18T20:27:28Z" finished-at="2017-01-18T20:27:28Z">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- TC003_checkGiftCardFunctionality -->
				<test-method status="FAIL"
					signature="teardown()[pri:0, instance:com.framework.testCases.TestCases@5f2108b5]"
					name="teardown" is-config="true" duration-ms="0" started-at="2017-01-18T20:27:28Z"
					finished-at="2017-01-18T20:27:28Z">
					<exception class="java.lang.NullPointerException">
						<full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.framework.pageFactory.TestBase.teardown(TestBase.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.NullPointerException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- teardown -->
			</class> <!-- com.framework.testCases.TestCases -->
		</test> <!-- Default test -->
	</suite> <!-- Default suite -->
</testng-results>
